apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: dev
  labels:
    app: webapp
    project: www
spec:
  replicas: 2
  selector:
    matchLabels:
      project: www
      app: webapp
  template:
    metadata:
      labels:
        project: www
        app: webapp
    spec:
      containers:
      - name: www
        image: bullmoon/herzliaproject:dev
        resources:
          limits:
            memory: 128Mi
            cpu: "1"
          requests:
            memory: 64Mi
            cpu: "0.2"
        ports:
        - containerPort: 9003